### ISSUE TITLE
`< ... />` seems to break highlighting

### ISSUE THREAD

**Issue by Dashed** [Benvie/JavaScriptNext.tmLanguage#56]
I'm embedding JSX stuff into ES6 source code, but highlighting borks with `< [stuff]  />`:

![screen shot 2015-01-02 at 6 55 06 pm](https://cloud.githubusercontent.com/assets/139499/5600789/f124b4de-92b0-11e4-9798-d46160762ce5.png)

Works fine if I remove the `/` (but this isn't valid JSX :cry: ):

![screen shot 2015-01-02 at 6 56 34 pm](https://cloud.githubusercontent.com/assets/139499/5600791/195d4bd2-92b1-11e4-88d3-9eb429e646ee.png)

**Comment by Dashed** [comment]
Also forgot to mention that I'm using the following color scheme: https://github.com/jonschlinkert/sublime-monokai-extended

**Comment by zertosh** [comment]
This PR (https://github.com/reactjs/sublime-react/pull/28) for `sublime-react` that adds JSX support on top of JavaScriptNext. Hopefully that'll get merged.

**Comment by simonzack** [comment]
@zertosh I had a look at the react package, and I mostly agree with @STRML's comment. If this package is going to support reactjs highlighting, it might as well support the whole thing, as I can't think of a way to separate them cleanly. Do you have any ideas on this?

**Comment by zertosh** [comment]
@simonzack: It'd be awesome if `JavaScriptNext` incorporated the JSX extensions, I'd be more than happy to put together a PR for that, but I can understand a desire to keep the two separate.

My `sublime-react` PR has remained unmerged for 56 days. However, if you look at the commit history, you'll see that I've been keeping it fresh with all your updates since then. If @jgebhardt is cool with merging it in, I'd be more than willing it keep it up-to-date with `JavaScriptNext`.

I see several ways forward:

1. `JavaScriptNext` incorporates the JSX extensions.
  Pros: One definition to rule them all hehe.
  Cons: ES6 support, which is the goal of `JavaScriptNext`, has nothing to do with JSX. Also, I think this might cause problems for `SublimeLinter-jsxhint` since `SublimeLinter` expects a syntax name. @STRML owns it, maybe he can help?

2. `sublime-react` merges my PR, and I manually keep it up-to-date with `JavaScriptNext`.
  Pros: Clean separation of definitions. Easy upgrade for people already using `sublime-react`.
  Cons: Manual merges - but I'm doing that now anyway. Our React code at SoundCloud is ES6. Those of us working on it are using my fork of `sublime-react`, so we're invested in keeping it fresh.

**Comment by Dashed** [comment]
Oh awesome, I hadn't noticed the PR (https://github.com/reactjs/sublime-react/pull/28).

Another solution I'm considering is forking `JavaScriptNext`, add the JSX extensions, and put it under the `6to5` umbrella: https://github.com/6to5 

I briefly brought this idea up in 6to5 Gitter chat and @sebmck seems open to it.

Semantically, I think this would be better moving forward since `6to5` officially supports JSX + ES6/7.
 
`JavaScriptNext` should really just support `ES6+`, and likewise, `sublime-react` should really just support JSX spec: http://facebook.github.io/jsx/#syntax A gotcha is that JSX only support specific ES6 features (even with `harmony` flag enabled).

@zertosh if you're open with this idea, I think @sebmck may be open to giving you read/write access to a `6to5-sublime` repo (or some other name) under the `6to5` organization; much like other plugins available in the org.

**Comment by sebmck** [comment]
@Dashed Definently open to that.

**Comment by zertosh** [comment]
@Dashed @sebmck: I'm totally open to that, but first, since `JavaScriptNext` and `sublime-react` are the established projects, I'd like to give @simonzack and @jgebhardt a chance to chime in first.
