### ISSUE TITLE
Object properties colored same as string

### ISSUE THREAD

**Issue by lukescott** [Benvie/JavaScriptNext.tmLanguage#59]
I'm using Spacegray/base16-eighties.dark.tmTheme and the property keys are showing up as the same color as strings. This doesn't happen in Go, for example, which shows the property as white.

![screen shot 2015-01-12 at 5 28 16 pm](https://cloud.githubusercontent.com/assets/486224/5714625/748acb20-9a80-11e4-9402-cb526ee33d85.png)

**Comment by simonzack** [comment]
This is scoped under `string.unquoted.label.js` since in javascript they're no different from strings. I don't know about the go syntax, but judging from your screenshot it appears to be classed under `entity`, which I don't think is quite appropriate for javascript. Give the `ScopeAlways` plugin a try. 

But you can easily modify your theme to change it to white or any color you like, so I don't think theres much of a reason for changing it here.
